module.exports = [
"pines group site - stony gorge reservoir",
"tuttletown recreation area",
"glory hole recreation area",
"oak shores day use area",
"crystal springs campground mid-sized group sites",
"sentinel campground",
"potwisha campground",
"buckeye flat campground",
"juniper lake group",
"manzanita lake camping cabins",
"butte lake stock corral",
"juniper lake stock corral",
"summit lake stock corral",
"point reyes national seashore campground",
"circle x ranch group campground",
"pinnacles campground",
"summit lake south",
"summit lake north",
"lost creek group",
"wawona",
"upper pines",
"tuolumne meadows",
"north pines",
"lower pines",
"hodgdon meadow",
"crane flat",
"bridalveil creek group and horse camp",
"whiskey creek group picnic area",
"dry creek group campground",
"dorst creek campground-sequoia and kings canyon national park",
"lodgepole campground-sequoia and kings canyon national park",
"sheep pass group",
"cottonwood group",
"indian cove campground",
"black rock campground",
"kirby cove campground",
"furnace creek",
"santa rosa island",
"santa cruz scorpion",
"santa cruz del norte backcountry",
"santa barbara island",
"san miguel island",
"anacapa island",
"sunset campground",
"canyon view group sites",
"coyote point",
"horse creek",
"chowchilla recreation area day use",
"chekaka recreation area lake mendocino",
"oak knoll campground",
"codorniz recreation area campground",
"bushay recreation area",
"buckhorn",
"buck ridge",
"hidden view",
"island park",
"kyen campground and oak grove day use area",
"liberty glen",
"orland buttes",
"tule",
"warm springs rec area",
"trimmer campground",
"pomo day use area",
"acorn campground",
"observation point picnic shelter",
"codorniz campground",
"hidden view campground",
"pine flat campground",
"san bernanrdino county recreation area",
"santa margarita lake recreation area",
"north tule campground",
"south tule campground",
"jackson point boat in campground",
"lindsey lake campground",
"woodchuck campground",
"madrone cove campground",
"snag lake campground",
"sterling lake campground",
"bowman road",
"pierce creek campground",
"gold lake road",
"robinson flat campground",
"garden point campground",
"mosquito ridge road",
"dark day campground",
"grouse ridge campground",
"bullards lakeshore campground",
"carr lake campground",
"schoolhouse campground",
"ahart campground",
"big reservoir campground",
"sagehen creek campground",
"marysville road",
"frenchy point campground",
"foresthill divide road",
"canyon creek campground",
"talbot campground",
"bowman campground",
"bear valley campground",
"poppy campground",
"jackson creek campground",
"meadow lake campground",
"dusty campground",
"crater lake",
"honn campground",
"silver bowl campground",
"warner creek campground",
"elam campground",
"battle creek campground",
"potato patch campground",
"hole-in-the-ground campground",
"rocky knoll campground",
"high bridge campground",
"roxie peconom campground",
"domingo springs campground",
"bridge campground",
"cave campground",
"butte meadows campground",
"rocky campground",
"goumaz",
"big pine campground",
"soldier meadows campground",
"bogard campground",
"laufman campground",
"feather falls trailhead campground",
"sundew campground",
"feather river canyon recreation area",
"haven lake campground",
"lake davis recreation area",
"other mt. hough campgrounds",
"goose lake campground",
"lower bucks campground",
"brady's camp campground",
"rogers cow camp",
"conklin park campground",
"meadow view equestrian campground",
"crocker campground",
"snake lake campground",
"indian valley area",
"other feather river campgrounds",
"beckwourth ranger district",
"horse camp",
"antelope lake recreation area",
"mill creek campground",
"gold lake 4x4 campground",
"golden trout",
"silver lake campground",
"gold lake campground",
"greenville campground",
"feather river ranger district",
"mt. hough ranger district",
"strawberry campground",
"queen lily campground",
"peninsula tent campground",
"little north fork campground",
"sly creek campground",
"bucks lake recreation area",
"rock creek campground",
"sly creek recreation area",
"gansner bar campground",
"meadow valley area",
"milsap bar campground",
"deanes valley campground",
"joe elliot yellow post sites",
"big bear yellow post sites",
"applewhite campground",
"paiute canyon yellow post sites",
"coon creek yellow post sites",
"dark canyon campground",
"gobbler's knob yellow post sites",
"santa rosa springs campground",
"tool box springs campground",
"stockton flats yellow post sites",
"tool box springs yellow post sites",
"lake arrowhead - green valley lake recreation area",
"keller peak yellow post sites",
"coldwater canyon yellow post sites",
"santa rosa & san jacinto mtns. national monument",
"south fork family campground",
"pinyon flat campground",
"santa rosa yellow post sites",
"holcomb valley campground",
"thomas hunting grounds yellow post sites",
"horse springs campground",
"clark's ranch yellow post site",
"san jacinto - santa rosa mountains recreation area",
"lytle creek - cajon pass recreation area",
"big pine flat family campground",
"big bear lake recreation area",
"white rock lake",
"lake of the woods",
"stampede reservoir - water recreation",
"wrights lake equestrian campground",
"red fir flat group campground",
"campgrounds - highway 108 corridor",
"almanor north campground",
"crocker guard station",
"sardine peak lookout",
"bear lake campground",
"blue lake campground",
"fowlers campground",
"medicine lake recreation area",
"howard meadows campground",
"ten mile campground",
"little beaver a campground",
"wyandotte a campground",
"mumford bar campground",
"aspen grove campground",
"pinecrest day use area",
"thunderbird group campground",
"halfway group campground",
"hidden horse equestrian campground",
"kennedy meadows campground",
"friis campground",
"nettle springs campground",
"brookshire campground",
"paradise campground",
"toad springs campground",
"mt. pinos ranger district",
"white oaks campground",
"nira campground",
"ballinger campground",
"marian campground",
"colson campground",
"navajo flat campground",
"rock camp campground",
"china camp campground",
"hi mountain campground",
"aliso park campground",
"middle santa ynez campground",
"ojai ranger district",
"memorial park campground",
"horseshoe springs campground",
"mono campground",
"middle lion campground",
"caballo campground",
"kings campground",
"la panza campground",
"davy brown campground",
"bottchers gap campround",
"reyes peak campground",
"goldhill camping area",
"campo alto campground",
"dome springs campground",
"santa lucia ranger district",
"baja campground",
"rose valley campground",
"lazy campground",
"p-bar flat campground",
"miranda pine campground",
"pine mountain campground",
"escondido campground",
"american canyon seasonal campground",
"valle vista campground",
"chula vista campground",
"reyes creek campground",
"halfmoon campground",
"bates canyon campground",
"dutchman campground",
"santa barbara ranger district",
"barrel springs campground",
"pine springs campground",
"thorn meadows campground",
"chuchupate campground",
"wagon flat campground",
"nacimiento campground",
"figueroa campground",
"monterey ranger district",
"mt. pinos campground",
"buck spring campground",
"wild horse equestrian family",
"lookout campground",
"oak grove campground",
"whitehorse campground",
"kit carson campground",
"juanita lake group campsite",
"fremont campground",
"south shore campground",
"boyington mill",
"boca campground",
"boca rest campground",
"boca spring",
"lakeside",
"calpine lookout",
"silver creek group campground",
"fashoda",
"bear river group campground",
"prosser family",
"frog meadow guard station",
"poso guard station cabin",
"mountain home guard station cabin",
"bear basin lookout and cabin",
"coldwater campground",
"convict lake campground",
"live oak south",
"wishon cabin",
"twin lakes campground",
"silver lake campground june lake",
"carter meadows horse group",
"nordheimer group sites",
"indian scotty group site",
"hirz mountain lookout",
"spanish creek campground",
"sarah totten campground",
"curly jack campground",
"girard ridge lookout",
"post creek guard station",
"forest glen guard station",
"little mt. hoffman lookout",
"tree of heaven campground",
"camp four and half cabin",
"mccarthy point lookout",
"ribbonwood equestrian cg",
"union flat",
"packsaddle",
"berger",
"diablo",
"cal-ida",
"sardine lake",
"salmon creek",
"loganville",
"fiddle creek",
"ramshorn",
"wild plum",
"sierra",
"chapman",
"carlton",
"indian valley",
"rocky rest",
"lightning point group campground",
"coulter group campground",
"bandido group campground",
"big bend group",
"skillman",
"indian springs",
"pearch creek campground",
"pine mountain lookout",
"oak bottom campground",
"sycamore grove campground",
"mad river campground",
"sly guard cabin",
"palisades group campground",
"upper stony creek campground",
"fish lake campground",
"dillon creek campground",
"dripping springs campground",
"little lasier meadows campground",
"boise creek",
"masterson group campground",
"gray pine group campground",
"lewis at french meadows",
"sandy flat",
"fir cove campground",
"reversed creek campground",
"camp 4 group campground",
"grouse valley",
"mary smith campground",
"alpine view campground",
"ackerman campground",
"minersville campground",
"pyramid lake - los alamos campground",
"ponderosa cove campground",
"black mountain lookout",
"observatory campground",
"pyramid lake - emigrant landing day use area",
"fry creek campground",
"oso group",
"lake mary campground",
"lake george",
"pine city",
"eshom campground",
"meadow group campground",
"four jeffrey",
"old shady rest campground",
"summerdale campground",
"dirt flat",
"dry gulch",
"new shady rest campground",
"paradise",
"south fork group",
"rock creek lake",
"quaking aspen cabin",
"shady cove group campground",
"capps crossing",
"fishermans group",
"tent peg group",
"los prietos",
"harvey west cabin",
"camp 9",
"running deer campground",
"horse campground",
"jackson flats",
"mountain oak",
"lake campground",
"big silver group",
"dimond o",
"pines group stanislaus",
"falcon group",
"boulder oaks eqst",
"crestline group",
"el prado group",
"horse heaven group",
"wooded hill group",
"middle meadows",
"wrights lake",
"obsidian flat",
"agnew meadows group camp",
"pumice flat group camp",
"arroyo seco",
"plaskett creek campground",
"sage hill",
"upper oso campground",
"mcgill campground",
"lakes basin",
"big pine equestrian group campground",
"bluff mesa group camp",
"boulder group camp",
"buttercup group camp",
"deer group camp",
"fern basin",
"grays peak group camp",
"ironwood group camp",
"juniper springs group camp",
"marion mountain",
"tanglewood group camp",
"barton flats",
"san gorgonio",
"prosser ranch group",
"black mountain",
"black oak",
"boulder basin",
"coon creek group campground",
"council",
"coyote group",
"dogwood",
"forbes creek",
"french meadows",
"gates group",
"gerle creek",
"grays meadows",
"green creek group",
"green valley",
"heart bar equestrian",
"honeymoon flat",
"ice house",
"lobo group",
"lone pine",
"loon lake",
"onion valley",
"paha",
"sunset-union valley",
"robinson creek north",
"skyline",
"stumpy meadows",
"trumbull lake",
"lower twin lakes at bridgeport",
"wench creek",
"whitney portal",
"yellowjacket",
"bass lake recreation area",
"dinkey creek",
"frenchman",
"wheeler gorge",
"faucherie",
"hope valley",
"mount rose",
"silver creek",
"hayward flat",
"tannery",
"big pine canyon",
"bishop park group",
"mcgee creek",
"rock creek lake group camp",
"table mountain",
"tuff campground",
"upper sage flat",
"grassy flat campground",
"almanor",
"eagle campground",
"hat creek",
"hanna flat",
"serrano",
"pinecrest",
"hampshire rocks",
"pipi campground",
"silver lake east- eldorado",
"tunnel mills ii",
"hallsted",
"hutchins",
"red feather california",
"june lake",
"oh ridge",
"pine glen",
"sherwin creek",
"burnt rancheria",
"laguna",
"pineknot",
"gurnsey creek",
"pioneer trail",
"heart bar campground",
"north shore",
"red fir",
"big pine creek campground",
"patrick creek campground",
"white cloud",
"panther flat campground",
"crystal lake",
"holiday group campground",
"lodgepole group lake alpine",
"loon lake chalet",
"robbs hut",
"green spot equestrian group camp",
"fawn",
"stoney group shasta-trinity",
"bushytail",
"wolf creek california",
"crags campground",
"yuba pass campground",
"crab flats",
"french camp",
"agnew horse camp",
"trailhead group",
"antlers",
"dekkas rock",
"goose meadows",
"fir top campground",
"findley campground",
"lakeshore east",
"woodcamp campground",
"bailey cove",
"ellery creek",
"hirz bay",
"moore creek",
"nelson point",
"pine point",
"pass creek campground",
"east meadow campground",
"nevada beach campground and day use pavilion",
"fallen leaf campground",
"white river",
"logger flat group",
"aspen hollow group",
"hume lake",
"princess",
"cove group",
"fir group",
"stony creek sequoia",
"french gulch",
"live oak",
"paradise cove",
"pioneer point",
"hungry gulch",
"boulder gulch",
"tillie creek",
"spring cove",
"lupine",
"jackass meadow",
"mono creek",
"mono hot springs",
"vermillion",
"wishon",
"badger flats group",
"belknap",
"upper billy creek cg",
"catavee",
"college",
"deer creek",
"kinnikinnick",
"rancheria",
"hospital flat",
"mammoth pool",
"rock creek",
"headquarters",
"fish creek",
"dorabelle campground",
"long meadow group",
"holey meadow",
"big cove",
"redwood meadow",
"chilcoot",
"quaking aspen",
"cottonwood",
"spring creek",
"grasshopper flat",
"lightning tree",
"grizzly",
"logger campground",
"emigrant group",
"cold creek",
"cottonwood creek",
"william kent campground",
"kaspian campground",
"meeks bay",
"sweetwater",
"forks campground",
"texas flats",
"kelty meadow",
"soquel campground",
"chilkoot",
"granite flat",
"silver creek-truckee",
"silvertip group",
"shirttail creek",
"giant gap",
"camp three campground",
"fairview campground",
"goldledge campground",
"coy flat",
"christie campground",
"merrill campground",
"lower billy creek",
"lower little truckee",
"upper little truckee",
"crane valley",
"recreation point",
"wishon bass lake",
"cedar bluff",
"lone rock",
"long point",
"boulder creek",
"west eagle campground",
"hirz bay group 1",
"hirz bay group 2",
"aspen group",
"robinson creek south",
"van vleck bunkhouse",
"kirk creek campground",
"cerro alto campground",
"ponderosa campground",
"cherry valley",
"lost claim",
"happy camp/oak knoll ranger district",
"beaver creek campground",
"fort goff campground",
"grider creek campground",
"mt. ashland campground",
"norcross campground",
"sulphur springs campground",
"west branch campground",
"klamath national wild & scenic river",
"salmon/scott river ranger district",
"east fork campground",
"hotelling campground",
"idlewild campground",
"matthews creek campground",
"mulebridge campground",
"red bank campground",
"hidden horse campground",
"kangaroo lake campground",
"lovers camp campground",
"salmon national wild & scenic river",
"bridge flat river access",
"goosenest ranger district",
"martins dairy campground",
"martins dairy horse camp",
"orr lake campground",
"shafter campground",
"china flat campground",
"silver fork campground",
"middle fork cosumnes campground",
"sugar pine point campground",
"caples lake campground",
"kirkwood campground",
"woods lake campground",
"mokelumne campground",
"west point campground",
"wentworth springs campground",
"northwind campground",
"strawberry point campground",
"northshore campground",
"pleasant campground",
"hell hole campground",
"camino cove campground",
"airport flat campground",
"jones fork campground",
"azalea cove campground",
"dru barner campground",
"sand flat campground",
"pardoes point campground",
"white azalea campground",
"lovers leap campground",
"moore campground",
"clark springs campground",
"cooper gulch campground",
"jackass springs campground",
"mariners roost boat-in campground",
"stoney point campground",
"tunnel rock campground",
"bridge camp campground",
"clear creek campground",
"eagle creek campground",
"east weaver campground",
"goldfield campground",
"horse flat campground",
"preacher meadow campground",
"rush creek campground",
"scott mountain campground",
"trinity river campground",
"big bar area",
"big bar campground",
"burnt ranch campground",
"hayden flat campground",
"hobo gulch campground",
"pigeon point campground",
"ripstein campground",
"denny campground",
"hayfork area",
"big slide campground",
"forest glen campground",
"hells gate campground",
"philpot campground",
"scotts flat campground",
"slide creek campground",
"shiell gulch campground",
"basin gulch campground",
"yolla bolla area",
"beegum gorge campground",
"deerlick springs campground",
"tomhead saddle campground",
"white rock campground",
"mt. shasta area",
"castle lake campground",
"gumboot campground",
"mcbride springs campground",
"panther meadows campground",
"sims flat campground",
"mccloud area",
"ahdina campground",
"algoma campground",
"fowlers camp campground",
"harris spring campground",
"trout creek campground",
"shasta lake area",
"gregory creek campground",
"lower jones valley campground",
"upper jones valley campground",
"mccloud bridge campground",
"deadlun campground",
"madrone campground",
"trinity lake/weaverville area",
"chirpchatter campground",
"smith river national recreation area",
"big flat campground",
"north fork campground",
"lower trinity ranger district",
"mad river ranger district",
"bailey canyon campground",
"orleans ranger district",
"aikens creek west campground",
"e-ne-nuck campground",
"nordheimer",
"ukonom ranger district",
"zephyr cove day use area",
"lake tahoe - east shore",
"camp shelly",
"zephyr cove resort & campground",
"lake tahoe - south shore",
"bayview campground",
"camp richardson",
"william kent day use area",
"lake tahoe - west shore",
"stonyford recreation area",
"dixie glade campground",
"letts lake campground",
"bear creek campground",
"upper lake recreation area",
"lake pillsbury",
"fuller grove campground",
"navy camp campground",
"oak flat campground",
"pogie point campground",
"sunset campground",
"yolla bolly-middle eel wilderness",
"green springs campground",
"rock cabin trailhead",
"red bluff recreation area",
"general campgrounds & trailheads",
"atchison campground",
"eel river campground",
"hammerhorn campground",
"kingsley glade campground",
"howard lake campground",
"little doe campground",
"plaskett meadows campground",
"sugarfoot glade campground",
"sugar spring campground",
"surveyors camp campground",
"three prong campground",
"wells cabin campground",
"whitlock campground",
"bobcat meadow campground",
"cibbets flat campground",
"corral canyon campground",
"indian flats campground",
"blue jay campground",
"el cariso campground",
"upper san juan campground",
"wildomar campground",
"el cariso visitor center",
"corral canyon area",
"mt. palomar north side area",
"san mateo wilderness south area",
"ortega highway area",
"evans flat campground",
"horse meadow campground",
"hobo campground",
"limestone campground",
"old isabella",
"lower peppermint campground",
"upper peppermint dispersed area",
"leavis flat campground",
"south fork rec campground",
"green cabin flat campground",
"horse camp campground",
"tenmile campground",
"landslide campground",
"mill flat campground",
"kern river ranger district",
"lower kern river",
"western divide ranger district",
"buck rock campground",
"convict flat campground",
"alder creek campground",
"auxiliary dam campground",
"breckenridge campground",
"brush creek campground",
"cedar creek campground",
"chico flat campground",
"corral creek campground",
"troy meadow campground",
"rancho nuevo campground",
"los angeles river ranger district",
"san gabriel river ranger district",
"buckhorn campground",
"horse flats campground",
"spring camp campground",
"oakwilde campground",
"mt. pacifico campground",
"appletree campground",
"big rock campground seasonal/hike-in",
"blue ridge campground",
"guffy campground",
"lupine campground-closed",
"santa clara/mojave rivers ranger district",
"peavine campground",
"southfork campground",
"sawmill campground--",
"spunky campground - closed",
"streamside campground - closed",
"upper shake campground - closed",
"bear campground--closed-powerhouse closure area",
"cienaga campground - closed",
"cottonwood campground--closed",
"live oak campground - decommissioned",
"messenger flats campground",
"monte cristo campground",
"zuni campground - closed",
"glenn camp campground",
"manker campground - closed for season",
"chilao campground - temporarily closed",
"basin campground - closed",
"lower chiquito campground",
"high sierra rd",
"voyager rock camping area",
"gigantea campground",
"buck meadow campground",
"sawmill flat campground",
"bretz mill campground",
"kirch flat campground",
"lily pad campground",
"swanson campground",
"sample meadow campground",
"badger flat campground",
"portal forebay campground",
"bolsillo campground",
"ward lake campground",
"west kaiser campground",
"whiskers campground",
"soda springs campground",
"placer campground",
"china bar camping area",
"upper chiquito campground",
"clover meadow campground",
"granite creek campground",
"whisky falls campground",
"little jackass campground",
"jerseydale campground",
"greys mountain campground",
"nelder grove campground",
"big sandy campground",
"fresno dome campground",
"mccabe flat campground",
"smalley cove campground",
"railroad flat campground",
"trapper springs campground",
"redinger campground",
"willow placer campground",
"marmot rock campground",
"kyle canyon road",
"lower virginia creek primitive campground",
"san juan campground",
"peavine creek campground",
"bob scott campground",
"big creek campground",
"kingston campground",
"lye creek campground",
"columbine campground",
"markleeville campground",
"bootleg campground",
"buckeye campground",
"sonora bridge campground",
"chris flat campground",
"leavitt meadows campground",
"toquima cave campground",
"obsidian campground",
"desert creek campground",
"green creek campground",
"upper virginia creek primitive campground",
"lower bluster campground",
"pavlak campground",
"pine creek campground",
"sawmill campground",
"upper bluster campground",
"jack creek campground",
"wildhorse crossing campground",
"centerville flat campground",
"cherry creek campground",
"lake alpine campground",
"mosquito lakes campground",
"highway 108 corridor",
"highway 4 corridor",
"campgrounds - highway 4 corridor",
"backpacker's camp",
"bloomfield campground",
"pacific valley campground",
"pine marten campground",
"silvertip campground",
"silver valley campground",
"stanislaus river campground",
"wild river campground",
"lake alpine recreation area",
"highland lakes",
"spicer reservoir",
"utica/union reservoirs",
"lumsden campground",
"lumsden bridge campground",
"south fork campground",
"sweetwater campground",
"pines campground",
"tuolumne wild & scenic river",
"fraser flat",
"hull creek",
"river ranch",
"sand bar flat",
"mi wok ranger district campgrounds",
"baker",
"beardsley dam",
"boulder flat",
"brightman flat",
"cascade creek",
"clark fork",
"dardanelle",
"deadman",
"eureka valley",
"fence creek",
"summit ranger district campgrounds",
"herring creek",
"meadowview",
"mill creek",
"niagara creek",
"pigeon flat",
"sand flat",
"herring reservoir",
"black oak",
"white mountains",
"grandview campground",
"sage flat campground",
"big trees campground",
"north lake campground",
"sabrina campground",
"forks campground",
"mountain glen campground",
"bitterbrush campground",
"intake 2 campground",
"willow campground",
"holiday campground",
"big meadow campground",
"mosquito flat backpacker campground",
"upper soda springs campground",
"pumice flat campground",
"minaret falls campground",
"reds meadow campground",
"hartley springs campground",
"gull lake campground",
"glass creek campground",
"big springs campground",
"deadman campground upper and lower",
"tioga lake campground",
"big bend campground",
"sawmill walk-in campground",
"ellery lake campground",
"junction campground",
"aspen grove campground",
"lower lee vining campground",
"upper grays meadow campground",
"cottonwood lakes trailhead campground",
"cottonwood pass trailhead campground",
"horseshoe meadow equestrian camp",
"horseshoe meadow area",
"bishop area",
"crowley lake/ rock creek area",
"mammoth ranger district",
"mammoth lakes area",
"reds meadow road",
"mono lake ranger district",
"lee vining/ mono lake",
"kern plateau",
"upper pine grove campground",
"iris meadow campground",
"bishop park campground",
"pine grove campground",
"schonchin springs campground",
"stough reservoir campground",
"patterson campground",
"mill creek falls campground",
"soup springs campground",
"ash creek campground",
"willow creek campground",
"lower rush creek campground",
"howard's gulch campground",
"medicine campground",
"hemlock campground",
"a.h. hogue campground",
"headquarters campground",
"payne springs campground",
"emerson campground",
"big sage campground",
"lassen creek campground",
"pepperdine campground",
"pepperdine equestrian campground",
"jane's reservoir campground",
"blanche lake campground",
"red tail rim trail south trailhead",
"warner mountain ranger district",
"big valley ranger district",
"devil's garden ranger district",
"bullseye lake campground",
"reservoir c campground",
"doublehead ranger district",
"east creek campground",
"blue lake campground",
"crystal springs campground",
"moraine campground",
"huntington lake recreation area",
"courtright/wishon recreation area",
"merced river recreation area",
"san joaquin river recreation area",
"dinkey creek recreation area",
"patterson mountain recreation area",
"kings river special management area",
"mammoth pool recreation area",
"high sierra recreation area",
"shaver lake recreation area",
"boulder reservoir",
"divine springs campground",
"fee reservoir",
"pit river campground",
"stevens camp",
"chimney peak wilderness",
"domeland wilderness",
"machesna wilderness",
"sacatar trail wilderness",
"santa lucia wilderness",
"pacific crest- owens peak segment",
"keysville",
"case mountaingiant sequoiaskaweah acec",
"san joaquin river gorge",
"chimney peak recreation area",
"walker pass campground",
"chimney creek campground",
"long valley campground",
"temblor recreation area",
"kcl campground",
"selby campground",
"yeh-gub-weh-tuh campground",
"aholul group campground",
"equestrian campground",
"bighorn mountain wilderness",
"black mountain wilderness",
"cleghorn lakes",
"funeral mountains",
"hollow hills wilderness",
"kingston range",
"nopah range",
"pinto mountain",
"saddle peak hills",
"south nopah range",
"bear mountain",
"panoche hills north",
"panoche hills south",
"clear creek",
"coalinga mineral springs",
"condon peak",
"curry mountain",
"griswold hills",
"laguna mountain",
"stockdale mountain",
"tumey hills",
"williams hill",
"gecko campground",
"roadrunner campground",
"keyhole campground",
"midway campground",
"clipper mountain wilderness",
"dead mountains wilderness",
"kelso dunes",
"north mesquite mountains wilderness",
"mesquite wilderness",
"sheephole valley",
"stateline wilderness",
"stepladder mountains",
"trilobite",
"turtle mountains",
"whipple mountains",
"amboy crater national natural landmark",
"boulder/balancing rock camp",
"camp ibis-patton",
"clark mountain camp",
"horsethief camp",
"ivanpah dry lake recreation area",
"camp clipper divisional camp -patton",
"iron mountain divisional camp -patton",
"blue cloud camping area",
"bonanza springs watchable wildlife area",
"castle rock hiking trail",
"cupcake mountain hiking trail",
"flattop mountain rock collecting area",
"lost arch historic mining camp",
"chambless rock collecting area",
"mopah peak hiking trail",
"snaggeltooth primitive rv camp",
"marble mountain rock collecting area",
"west well",
"savahia peak rock collecting area",
"historic route 66 california gateway site day use area",
"horsethief springs/cabin",
"buffalo hills",
"dry valley rim",
"five springs",
"skedaddle",
"tunnison mountain",
"twin peaks",
"bizz johnson national recreation trail",
"north eagle lake campground",
"rocky point primitive camping area",
"dodge reservoir campground",
"ramhorn springs campground",
"eagle lake",
"malpais mesa wilderness",
"surprise canyon",
"sylvania mountains",
"horton creek campground",
"crowley lake campground",
"pv pit campground",
"jawbone canyon ohv area",
"dove springs ohv area",
"shasta campground",
"steiner flat primitive campground",
"steel bridge campground",
"junction city campground",
"douglas city campground",
"buttercup ranger station",
"cahuilla ranger station",
"wiley well district geode beds",
"pilot knob long term visitor area",
"tamarisk long term visitor area",
"hot springs long term visitor area",
"cottonwood campground",
"lacks creek management area",
"massacre ranch recreation area",
"red canyon petroglyphs",
"san joaquin river gorge visitor center",
"ord mountain",
"rainbow basin/owl canyon campground",
"el mirage ohv area",
"dumont dunes ohv area",
"rasor ohv area",
"johnson valley ohv area",
"granite mountain",
"granite mountain trail",
"pat keyes trail",
"movie road",
"tuttle creek campground",
"midland long term visitor area",
"mojave trails national monument",
"bakersfield recreation sites",
"north fork kaweah river",
"bishop field office recreation sites",
"alabama hills",
"south yuba recreation area",
"san joaquin river gorge special recreation management area",
"ridgecrest recreation management area",
"spangler/red mountain",
"barstow field recreation sites",
"el mirage recreation management area",
"rasor off-highway vehicle area",
"alturas recreation area",
"arcata recreation management area",
"cow mountain recreation management area",
"johnson valley off-highway vehicle recreation area",
"juniper flats",
"cache creek recreation area",
"redding recreation management area",
"surprise recreation management area",
"high rock canyon",
"owens peak wilderness",
"panoche tumey hills",
"red elephant mine trail",
"trona pinnacles",
"volcanic tablelands",
"stoddard valley ohv area",
"indian creek recreation area",
"san gorgonio wilderness",
"santa rosa wilderness",
"argus range wilderness",
"bright star wilderness",
"cache creek wilderness",
"cedar roughs wilderness",
"coso range wilderness",
"darwin falls wilderness",
"el paso mountains wilderness",
"golden valley wilderness",
"grass valley wilderness",
"high rock canyon wilderness",
"manly peak wilderness",
"orocopia mountains wilderness",
"pahrump valley wilderness",
"piper mountain willderness",
"piute mountains wilderness",
"resting spring range wilderness",
"rodman mountains wilderness",
"stepladder mountains wilderness",
"trilobite wilderness",
"turtle mountains wilderness",
"whipple mountains wilderness",
"pacific crest national scenic trail",
"carrizo plain national monument",
"santa rosa and san jacinto mountains national monument",
"california desert conservation area",
"king range national conservation area",
"inyo mountains wilderness",
"kiavah wilderness",
"lake solano",
"sly park reservoir",
"sugar pine reservoir",
"folsom lake",
"lake berryessa",
"lake cahuilla",
"lake casitas",
"lewiston national recreation area",
"los banos reservoir",
"millerton lake",
"new melones lake",
"nimbus fish hatchery",
"boca reservoir",
"cachuma lake",
"trinity lake",
"east park reservoir",
"o'neill forebay",
"red bluff div. dam & reservoir",
"shasta national rec. area",
"squaw leap mgmt. area",
"stampede reservoir",
"stony gorge reservoir",
"bradshaw trail",
"greater farallones national marine sanctuary",
"monterey bay national marine sanctuary",
"castle mountains national monument",
"channel islands national park",
"devils postpile national monument",
"death valley national park",
"golden gate national recreation area",
"joshua tree national park",
"juan bautista de anza national historic trail",
"lava beds national monument",
"lassen volcanic national park",
"mojave national preserve",
"point reyes national seashore",
"presidio of san francisco",
"pinnacles national park",
"redwood national and state parks",
"santa monica mountains national recreation area",
"sequoia & kings canyon national parks",
"whiskeytown national recreation area",
"yosemite national park",
"success lake",
"prado dam",
"santa margarita lake",
"salt point sp",
"emerald bay",
"example that nobody will evr say"



    
]